// Generated by gencpp from file simple_arm/GoToPositionRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_ARM_MESSAGE_GOTOPOSITIONREQUEST_H
#define SIMPLE_ARM_MESSAGE_GOTOPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_arm
{
template <class ContainerAllocator>
struct GoToPositionRequest_
{
  typedef GoToPositionRequest_<ContainerAllocator> Type;

  GoToPositionRequest_()
    : joint_1_position(0.0)
    , joint_2_position(0.0)  {
    }
  GoToPositionRequest_(const ContainerAllocator& _alloc)
    : joint_1_position(0.0)
    , joint_2_position(0.0)  {
  (void)_alloc;
    }



   typedef double _joint_1_position_type;
  _joint_1_position_type joint_1_position;

   typedef double _joint_2_position_type;
  _joint_2_position_type joint_2_position;





  typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPositionRequest_

typedef ::simple_arm::GoToPositionRequest_<std::allocator<void> > GoToPositionRequest;

typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest > GoToPositionRequestPtr;
typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest const> GoToPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_arm::GoToPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1464c55039e16844dece818b4f76d730";
  }

  static const char* value(const ::simple_arm::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1464c55039e16844ULL;
  static const uint64_t static_value2 = 0xdece818b4f76d730ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_arm/GoToPositionRequest";
  }

  static const char* value(const ::simple_arm::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 joint_1_position\n\
float64 joint_2_position\n\
";
  }

  static const char* value(const ::simple_arm::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_1_position);
      stream.next(m.joint_2_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_arm::GoToPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_1_position: ";
    Printer<double>::stream(s, indent + "  ", v.joint_1_position);
    s << indent << "joint_2_position: ";
    Printer<double>::stream(s, indent + "  ", v.joint_2_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_ARM_MESSAGE_GOTOPOSITIONREQUEST_H
